name: ml_alg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas==1.5.1
  - numpy==1.23.4
  - matplotlib==3.6.0
  - scikit-learn==1.1.3
  - statsmodels==0.13.2
  - seaborn==0.12.1
  - scipy==1.9.3
  - jupyter~=1.0
  - jupyterlab==3.5.0